### ISSUE TITLE
Typing with keyboard conflicts with pad shortcuts

### ISSUE THREAD

**Issue by izzyreal** [izzyreal/mpc#267]
For example, when you want to type the letter Z in the Name window, usually this key is already assigned to pad 1, which can also be used to type a name (like on the real MPC2000XL).

I suggest to keep the pad typing possibility, but ony for MIDI input.

**Comment by c3ntr0n800** [comment]
I agree with this being something you can choose depending on what you would prefer. But if that would be too complicated to implement, then I'm more than fine with typing just being restricted to the way it works on real hardware.

**Comment by izzyreal** [comment]
Resolved by making it configurable and by not processing keyboard events twice. See the commit message of https://github.com/izzyreal/mpc/commit/3bb1788e1ca260a18a820fdcc20f1cd59316b57a for more info.

I'll make it part of the upcoming release candidate, which I aim to publish within a few days up to a week. Let me know if you'd like to get a preview so you can try it out before that.

**Comment by izzyreal** [comment]
> A bit confused as to why my issue got marked as a duplicate

You created the issue in https://github.com/izzyreal/vmpc-juce, but it belongs in https://github.com/izzyreal/mpc (my bad -- this setup is confusing, but it's not simple to change at this point). So I created a new issue in the `mpc` repo, which is the issue we're now discussing in. One of these 2 issues had to be marked as a duplicate of the other one, so it's clear why it got closed. Does this make sense?

> I'm in no hurry though, I can wait for the next release.

Nice one 👍 And thanks for reporting the problem!

**Comment by c3ntr0n800** [comment]
Just saw that you came out with a new release candidate, and I can confirm that typing has been fixed! I was finally able to rename some things in my recent projects, so I appreciate that! 

Most of the conflicts I was experiencing appear to be **mostly** taken care of, except for these two: 

It still occurs when moving the cursor left and right, regardless of toggling the typing modes or pressing the cursor keys on the UI. I started thinking that _maybe_ the config was busted, so I uninstalled and remove any traces of the program's files, then reinstalled the entire program to see if that would make any difference, but it didn't. You said this doesn't happen on your end however, so... yeah I'm stumped on this one. Maybe my PC has a grudge with me lol.

Left shift also seems to generally act strange, but that can be easily worked around by using right shift instead.

Aside from those, great job on this update! It's easier for me to use now. 👍

**Comment by c3ntr0n800** [comment]
> Are you aware of the location of the keyboard config file? You could try ditching those. See https://vmpcdocs.izmar.nl/0.9.0.0/install.html#file-locations
Alternatively you can try resetting the keyboard config in the KEYBRD screen. Shift + 0 and then F2 gets you there, and then you press F5 to reset the config:

I did attempt that before uninstalling and deleting its leftover files. (Which I read this page to see where all those files are.) Neither made a difference unfortunately...

> I'd be happy to dig deeper whenever you're up for that. Best create a new ticket for the cursor issue, and another one for the one about the shift key.

What should I write in those OPs? Just what I have been experiencing? I won't be much further help in figuring this out, as I don't have much to add... aside from testing VMPC outside of my main PC. (Which in my situation would be through VMs. My other PCs are unavailable to access.)

> When creating the new tickets it might be helpful to also note the DAW and OS version too, in case others with similar systems can confirm experiencing the same issue, and also to check if the same issues occur on the standalone version?

In the OP of the "duplicate" issue, I mentioned that my PC is running Windows 10 Pro 22H2. I did forget to specify that I mainly use the standalone version, but from my testing, this is a bug in both the standalone and VST versions.
